### ISSUE TITLE
adding an extension to the URL should return an image converted to that format

### ISSUE THREAD

**Issue by mhl** [jpmckinney/image-proxy#12]
This is a small feature request: most of the large images of candidates on YourNextMP's images are stored as PNG files, but it would nice to be able to get a JPEG thumbnail by adding .jpg to the URL requested. So at the moment, this thumbnail returns a PNG:

* https://yournextmp.popit.mysociety.org/image-proxy/http%3A%2F%2Fyournextmp.popit.mysociety.org%2Fpersons%2F4493%2Fimage%2F5481e8f6b150e238702c061b/0/64

... but it would be great if you could get a JPEG by requesting:

* https://yournextmp.popit.mysociety.org/image-proxy/http%3A%2F%2Fyournextmp.popit.mysociety.org%2Fpersons%2F4493%2Fimage%2F5481e8f6b150e238702c061b/0/64.jpg

... or something similar.

**Comment by jpmckinney** [comment]
Let me know if this works, and I'll release to npm.
