### ISSUE TITLE
Some images suffer gamma distortion on resize

### ISSUE THREAD

**Issue by lizconlan** [jpmckinney/image-proxy#13]
In a few rare cases, images served through the proxy can look much too dark after they've been resized. It appears that it might be fixable by passing colorspace('RGB') to imageMagick as per http://www.imagemagick.org/Usage/resize/#resize_colorspace (although I'm not sure if that could be considered harmful if left on all the time).

As an example...

Before:

![image](https://cloud.githubusercontent.com/assets/27760/7185935/09b8f9e8-e45e-11e4-8d05-a2355906c8a3.png)

After:

![image](https://cloud.githubusercontent.com/assets/27760/7185949/2e45c6a6-e45e-11e4-8659-97a013cbfedd.png)

More info here: https://github.com/mysociety/yournextmp-popit/issues/288

**Comment by jpmckinney** [comment]
Thanks for the docs @lizconlan !

**Comment by lizconlan** [comment]
Thanks for the quick fix @jpmckinney! :grinning:

**Comment by benmarten** [comment]
Issue is also on heroku, due to old imagemagick version. I use this build pack to solve the problem: https://github.com/ello/heroku-buildpack-imagemagick-cedar-14

**Comment by jpmckinney** [comment]
Thanks @benmarten, I've added the buildpack: https://github.com/jpmckinney/image-proxy/commit/aad252f0f179067dbc44694283005ce26b308484
